"""add_job_desc_fields_to_resume

Revision ID: d44d447debda
Revises: '49c239a21708'
Create Date: 2026-08-29 10:57:44.483311+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d44d447debda"
down_revision: Union[str, None] = "49c239a21708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("target_role", sa.Text(), nullable=True))
    op.add_column("resumes", sa.Column("target_company", sa.Text(), nullable=True))
    op.add_column("resumes", sa.Column("job_description_text", sa.Text(), nullable=True))
    op.add_column("resumes", sa.Column("job_description_source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "job_description_source")
    op.drop_column("resumes", "job_description_text")
    op.drop_column("resumes", "target_company")
    op.drop_column("resumes", "target_role")
    # ### end Alembic commands ###
